"""first migration

Revision ID: d98aec5cb13b
Revises: 
Create Date: 2024-09-26 11:32:08.744165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd98aec5cb13b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sdb_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kpi', sa.String(length=100), nullable=False),
    sa.Column('Device', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('max_value', sa.String(length=100), nullable=False),
    sa.Column('min_value', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('site', sa.String(length=100), nullable=False),
    sa.Column('building', sa.String(length=100), nullable=False),
    sa.Column('floor', sa.String(length=100), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sdb_alerts_id'), 'sdb_alerts', ['id'], unique=False)
    op.create_table('sdb_aqi_hour',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aqi', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.String(length=100), nullable=False),
    sa.Column('end_date', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sdb_aqi_hour_id'), 'sdb_aqi_hour', ['id'], unique=False)
    op.create_table('sdb_iaq',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('site', sa.String(length=100), nullable=False),
    sa.Column('building', sa.String(length=100), nullable=False),
    sa.Column('floor', sa.String(length=100), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sdb_iaq_id'), 'sdb_iaq', ['id'], unique=False)
    op.create_table('sdb_rule_engine',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kpi', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.String(length=100), nullable=False),
    sa.Column('max_value', sa.String(length=100), nullable=False),
    sa.Column('min_value', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('device', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sdb_rule_engine_id'), 'sdb_rule_engine', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=1024), nullable=True),
    sa.Column('dept', sa.String(length=255), nullable=True),
    sa.Column('emp_id', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('dob', sa.String(length=20), nullable=True),
    sa.Column('doj', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('is_active', mysql.TINYINT(), nullable=True),
    sa.Column('is_neglated', mysql.TINYINT(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('user_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=1024), nullable=True),
    sa.Column('dept', sa.String(length=255), nullable=True),
    sa.Column('emp_id', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('dob', sa.String(length=20), nullable=True),
    sa.Column('doj', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('is_active', mysql.TINYINT(), nullable=True),
    sa.Column('is_neglated', mysql.TINYINT(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_logs_id'), 'user_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_logs_id'), table_name='user_logs')
    op.drop_table('user_logs')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_sdb_rule_engine_id'), table_name='sdb_rule_engine')
    op.drop_table('sdb_rule_engine')
    op.drop_index(op.f('ix_sdb_iaq_id'), table_name='sdb_iaq')
    op.drop_table('sdb_iaq')
    op.drop_index(op.f('ix_sdb_aqi_hour_id'), table_name='sdb_aqi_hour')
    op.drop_table('sdb_aqi_hour')
    op.drop_index(op.f('ix_sdb_alerts_id'), table_name='sdb_alerts')
    op.drop_table('sdb_alerts')
    # ### end Alembic commands ###
