"""second migration

Revision ID: f1fb8b0eb636
Revises: d98aec5cb13b
Create Date: 2024-09-27 10:40:30.440243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1fb8b0eb636'
down_revision: Union[str, None] = 'd98aec5cb13b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sdb_temp_hour',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Temp', sa.String(length=100), nullable=False),
    sa.Column('Hum', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.String(length=100), nullable=False),
    sa.Column('end_date', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sdb_temp_hour_id'), 'sdb_temp_hour', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sdb_temp_hour_id'), table_name='sdb_temp_hour')
    op.drop_table('sdb_temp_hour')
    # ### end Alembic commands ###
